import Head from "next/head";
import React from "react";
import PageLayout from "../lib/components/PageLayout";
import VideoCard from "../lib/components/VideoCard";

const index = () => {
  return (
    <div>
      <Head>
        <title>Youtube Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout activeLink="/">
        <VideoCard />
      </PageLayout>
    </div>
  );
};

export default index;
